# Generated by Django 5.0.1 on 2024-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_userproduct_id_alter_userproduct_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
