# Generated by Django 5.0.1 on 2024-01-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_userproduct_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
