# Generated by Django 5.0.1 on 2024-01-13 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_useravatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="userAvatar",
        ),
    ]
