# Generated by Django 5.0.1 on 2024-01-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_userproduct_id"),
        ("user", "0003_remove_user_useravatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="products",
            field=models.ManyToManyField(
                null=True, related_name="users", to="product.userproduct"
            ),
        ),
    ]
