# Generated by Django 5.0.1 on 2024-01-12 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAvatar", "0002_useravatar_created_at_useravatar_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="useravatar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
