# Generated by Django 5.0.1 on 2024-01-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAvatar", "0004_alter_useravatar_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useravatar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="useravatar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
